name: 'DeleteTagAndRelease'
description: 'GitHub action to delete tags and/or releases'
author: 'RandLabs Inc.'

branding:
  color: "red"
  icon: "delete"

inputs:
  tag:
    description: 'Tag name.'
    required: true
  delete_release:
    description: 'Set to true to indicate if the release must be deleted.'
    required: false
    default: 'true'
  delete_tag:
    description: 'Set to true to indicate if the tag must be deleted (implies release deletion too).'
    required: false
    default: 'true'
  repo:
    description: 'Target repository in <owner-or-company>/<repository> format. Defaults to the one that fired the action.'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
